title: "AllSpec"
description: "Plataforma integral para el tratamiento de datos espectroscópicos."
url: "https://guillermo-rr.github.io/AllSpec"
baseurl: "/AllSpec" 
author:
  name: "Guillermo Reyna Rodríguez"


remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

nav:
  - title: "Inicio"
    url: /
  - title: "Acerca de"
    url: /about/
  - title: "Instalación"
    url: /installation/
  - title: "Ejemplos"
    url: /examples/
  - title: "Contacto"
    url: /contact/

logo: "/assets/images/logo.png"

author:
  name: "Guillermo Reyna Rodríguez"
  bio: "Licenciado en Química especializado en ciencia de los nanomateriales y espectroscopía."
  links:


footer:
  links:
    - label: "GitHub "
      icon: "fab fa-github"
      url: "https://github.com/Guillermo-RR"
    - label: "LinkedIn "
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/guillermo-reyna-rodriguez-734403390/"
    - label: "ResearchGate "
      icon: "ai ai-researchgate"
      url: "https://www.researchgate.net/profile/Guillermo-Reyna-Rodriguez"
    - label: "Licencia MIT "
      url: "https://github.com/Guillermo-RR/AllSpec/blob/main/LICENSE"

  copyright: "© 2025 Guillermo Reyna Rodríguez. Powered by Jekyll & Minimal Mistakes."

# Configuración de layout amplio para todo el sitio
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      classes: wide

# === Importar CSS personalizado ===
sass:
  style: compressed

#include:
  - assets/css
include:
  - _includes
  - assets
